### ISSUE TITLE
Part 3: Tech

### ISSUE THREAD

**Issue by anasschaaraoui** [DevC-Casa/stateofdev.ma#1]
Hello DevC,

First of all, thank u for this initiative I really appreciate it, and I know how this will impact out community because at a certain time I needed such information but unfortunately I couldn't find any that's why am contributing in filling the survey + why not contributing to this beautiful initiative programmatically.

my issue that when I came to answer the 6th question in the part 3: tech I couldn't find any platform nor tool am using on my daily basis and by being honest as u asked at the beginning of the survey I cannot move forward any more.

Best Regards.
![image](https://user-images.githubusercontent.com/25872107/96625636-5c0cb400-1306-11eb-807d-bd0455fa876f.png)

**Comment by yjose** [comment]
thank you  @anasschaaraoui for your feedback, fixed
