### ISSUE TITLE
feature: order results in playground by value (highest to lowest)

### ISSUE THREAD

**Issue by naoufalelh** [DevC-Casa/stateofdev.ma#24]
## Description

In the playground, can we have by default the results ordered from highest voted to lowest.

## Current behavior

No order in the current playground

<img width="600" alt="Screen Shot 2020-12-14 at 13 55 35" src="https://user-images.githubusercontent.com/10200999/102083743-56b67c00-3e14-11eb-9bd3-54dac8f9ea3f.png">

## Expected behavior

To see the results after each filtering, and by default, ordered by the number of votes.

Example: from the same screenshot. I would like to see `React.js` then `jQuery` then `Other` ...

## Notes
I would like to thank everyone behind the survey and this website.

**Comment by yjose** [comment]
Hey @naoufalelh ,  sporting results is the default behavior for all charts in website unless you set sirt prop to false. 

In the first version of the playground we sort choices as you suggest but we noticed that it's hard to notice different between results on condition update. 

So we agree to not sort results at all as is a little bit confusing 🙏
