### ISSUE TITLE
"What is your current role" question is duplicated two sections

### ISSUE THREAD

**Issue by boredabdel** [DevC-Casa/stateofdev.ma#44]
This question "What is your current role" exist in both the profile and work yaml files. and the question has different replies.

Is this normal or a mistake ?

**Comment by AbderrahimSoubaiElidrissi** [comment]
@boredabdel I think it's not a duplication because of the difference between choices.
I will provide a PR to fix the one in the profile section

**Comment by AbderrahimSoubaiElidrissi** [comment]
Small fix to this https://github.com/DevC-Casa/stateofdev.ma/pull/46
