### ISSUE TITLE
confusing answer choices : question 6. How many years have you been coding professionally?

### ISSUE THREAD

**Issue by ans1genie** [DevC-Casa/stateofdev.ma#64]
the answers to `question 6. How many years have you been coding professionally?` looks to be confusing:

![image](https://user-images.githubusercontent.com/16513804/140500196-03605450-f4a9-4eea-a4c5-57965593bfda.png)

the actual values:
less than 1 year
1 to 2
3 to 4
5 to 6
..

the intervals look confusing, how can express more than 2 years of experience and less than 3? 
same for: 4 -to> 5 , 6 -to> 7 ..

**Comment by yjose** [comment]
Hmm we think it's clear @ans1genie , for example, if you have 2.5 years of experience it's clear that you need to select 1 - 2 option. 
but thank you for reporting this maybe we should try to make it more clear next time

**Comment by ans1genie** [comment]
Ok, I understand it now, so basically, since you have 1.x or 2.x it's in the range of 1 - 2. same for other ranges.
Makes sense for me. 
thanks for the explanation @yjose :D
